################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_MOSQUITTO "mosquitto")
    if (NOT PC_MOSQUITTO_FOUND)
        pkg_check_modules(PC_MOSQUITTO "mosquitto")
    endif (NOT PC_MOSQUITTO_FOUND)
    if (PC_MOSQUITTO_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_MOSQUITTO_CFLAGS} ${PC_MOSQUITTO_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_MOSQUITTO_INCLUDE_HINTS ${PC_MOSQUITTO_INCLUDE_DIRS} ${PC_MOSQUITTO_INCLUDE_DIRS}/*)
        set(PC_MOSQUITTO_LIBRARY_HINTS ${PC_MOSQUITTO_LIBRARY_DIRS} ${PC_MOSQUITTO_LIBRARY_DIRS}/*)
    endif(PC_MOSQUITTO_FOUND)
endif (NOT MSVC)

find_path (
    MOSQUITTO_INCLUDE_DIRS
    NAMES mosquitto.h
    HINTS ${PC_MOSQUITTO_INCLUDE_HINTS}
)

find_library (
    MOSQUITTO_LIBRARIES
    NAMES mosquitto
    HINTS ${PC_MOSQUITTO_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    MOSQUITTO
    REQUIRED_VARS MOSQUITTO_LIBRARIES MOSQUITTO_INCLUDE_DIRS
)
mark_as_advanced(
    MOSQUITTO_FOUND
    MOSQUITTO_LIBRARIES MOSQUITTO_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
